### ISSUE TITLE
interoptest/testcoordinator: validate reconstructed traces against requests

### ISSUE THREAD

**Issue by rghetia** [census-ecosystem/opencensus-experiments#133]
compare reconstructed traces agains the requests. If the request was from A to B to C then the trace should have root traceID from A and spans in order (A-client, B-server, B-client, C-server).

**Comment by songy23** [comment]
One optimization we can make is to only do the verification until all test cases finished (instead of doing verification for each test). This way we don't need to wait for some period of time in between test cases. See https://github.com/census-ecosystem/opencensus-experiments/pull/154#discussion_r246586586.

**Comment by rghetia** [comment]
that works.
